#!/usr/bin/env bash

suckdiff &&
git checkout master
git branch -D custom 
git branch custom &&
git checkout custom &&
for branch in $(git for-each-ref --format='%(refname)' refs/heads/ | cut -d'/' -f3); do
	if [ "$branch" != "master" ] && [ "$branch" != "custom" ];then
		git rebase --rebase-merges $branch
	fi
done
make && sudo make clean install &&
git checkout master &&
git branch -D custom &&
make clean && rm -f config.h && git reset --hard origin/master

#### ! ERROR !
# If this errors happend 
	# fatal: It seems that there is already a rebase-merge directory [...]
# To solve it:
	# git config --global user.email "you@email.com"
	# git config --global user.name "your name"