#!/usr/bin/env bash

suckdiff &&
git branch -D custom 
git branch custom &&
git checkout custom &&
for branch in $(git for-each-ref --format='%(refname)' refs/heads/ | cut -d'/' -f3); do
	if [ "$branch" != "master" ] && [ "$branch" != "custom" ];then
		git rebase --rebase-merges $branch
	fi
done
make && sudo make clean install &&
git checkout master &&
git branch -D custom &&
make clean && rm -f config.h && git reset --hard origin/master

#### ERROR !

# fatal: It seems that there is already a rebase-merge directory, and
# I wonder if you are in the middle of another rebase.  If that is the
# case, please try
#         git rebase (--continue | --abort | --skip)
# If that is not the case, please
#         rm -fr ".git/rebase-merge"
# and run me again.  I am stopping in case you still have something
# valuable there.