#!/usr/bin/env bash

git checkout master &&
difffiles="$HOME/.local/.suckdiffs/"
project=$(basename $(pwd))
diffdir="${difffiles}/${project}_diffs/"
olddiffdir="${difffiles}/${project}_diffs/old/"
rm -rf "$olddiffdir" &&
mkdir -p "$olddiffdir" &&
mkdir -p "$diffdir" &&
mv "$diffdir"*.diff "$olddiffdir" || true &&
make clean && rm -f config.h && git reset --hard origin/master && 
for branch in $(git for-each-ref --format='%(refname)' refs/heads/ | cut -d'/' -f3); do
	if [ "$branch" != "master" ];then
		git diff master..$branch > "${diffdir}${project}_${branch}.diff"
	fi
done
